### ISSUE TITLE
ライセンスがない問題

### ISSUE THREAD

**Issue by kamera25** [b111081/sample_app#1]
面白そうなプロジェクトやってますね。頑張ってください  
     
さてさて、サンプル系のプロジェクトでも License.md を作って
入れておいた方が良いですよ。無記入だと何をしてもOKという事で
変な利用をされる事があるので。    

[ここの補足3にも書いてあります](http://qiita.com/tadsan/items/99d816e78ca429093b75)が、自分の書いた
プログラムに対してライセンスを明記する事は重要ですよ。

**Comment by b111081** [comment]
会社でRailsチュートリアルやっとりましてね。

誰も見てないからいいやろと思うけど、一応入れときます。

2015年4月19日 19:47 Takahiro Nakaoku <notifications@github.com>:

> 面白そうなプロジェクトやってますね。頑張ってください
>
> さてさて、サンプル系のプロジェクトでも License.md を作って
> 入れておいた方が良いですよ。無記入だと何をしてもOKという事で
> 変な利用をされる事があるので。
>
> ここの補足3にも書いてあります <http://qiita.com/tadsan/items/99d816e78ca429093b75>
> が、自分の書いた
> プログラムに対してライセンスを明記する事は重要ですよ。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/b111081/sample_app/issues/1>.
>



-- 
島根県 松江市 西川津町 787-14

直江 駿一
hitsolb111081@gmail.com

**Comment by kamera25** [comment]
了解です。:+1: 
> 会社でRailsチュートリアルやっとりましてね。

羨ましいなー、うちも明日から周りにGithub使わせる活動してみよ。(嘘

**Comment by b111081** [comment]
テスト駆動開発とかいう闇に飲まれそうです。

Githubは広めても使う場がないやろな・・・


ところでライセンスの名前はGithubのアカウント名でいいんだよね。

2015年4月19日 19:57 Takahiro Nakaoku <notifications@github.com>:

> 了解です。[image: :+1:]
>
> 会社でRailsチュートリアルやっとりましてね。
>
> 羨ましいなー、うちも明日から周りにGithub使わせる活動してみよ。(嘘
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/b111081/sample_app/issues/1#issuecomment-94264363>.
>



-- 
島根県 松江市 西川津町 787-14

直江 駿一
hitsolb111081@gmail.com

**Comment by kamera25** [comment]
ぶっちゃけ、テスト駆動開発って流行すぎた感ある技術やで…(早いなぁ)

> ところでライセンスの名前はGithubのアカウント名でいいんだよね。
大丈夫です。とりあえず分かれば良いので。

**Comment by b111081** [comment]
テストが通らなくて頭抱えて・・・直して・・・抱えて・・・の繰り返しで辛い

ライセンスの件承知した。ありがとさん。

息抜きにオイラーの問題でもやってみたらどうっすかね。

2015年4月19日 20:10 Takahiro Nakaoku <notifications@github.com>:

> ぶっちゃけ、テスト駆動開発って流行すぎた感ある技術やで…(早いなぁ)
>
> ところでライセンスの名前はGithubのアカウント名でいいんだよね。
> 大丈夫です。とりあえず分かれば良いので。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/b111081/sample_app/issues/1#issuecomment-94265826>.
>



-- 
島根県 松江市 西川津町 787-14

直江 駿一
hitsolb111081@gmail.com

**Comment by kamera25** [comment]
うす。

> 息抜きにオイラーの問題でもやってみたらどうっすかね。

競技用プログラミングとか楽しいよね。時間内に解ける気はしないけど…

**Comment by b111081** [comment]
時間制限設けられたら死ぬわ。

時間が出来たらgithubのクソみたいなコード直さんとな・・・

もう広島には戻ったんだっけ？山口？

2015年4月19日 20:40 Takahiro Nakaoku <notifications@github.com>:

> うす。
>
> 息抜きにオイラーの問題でもやってみたらどうっすかね。
>
> 競技用プログラミングとか楽しいよね。時間内に解ける気はしないけど…
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/b111081/sample_app/issues/1#issuecomment-94268418>.
>



-- 
島根県 松江市 西川津町 787-14

直江 駿一
hitsolb111081@gmail.com
